"""
hardware_driver_v2.py
======================
Advanced module for real-time (in-matter) hardware interfacing, v2.
Integrates the optimal laboratory parameters derived from the simulation campaign
(P0_Distilled v0.1):
  - Compliance voltage/current to avoid device breakdown (SiO2:Ag / VO2 Mott)
  - 1/f percolative noise calibrated at the edge of chaos (sigma_noise = 0.10, alpha = 1.0)
  - Automatic pre-configuration for Keithley DMM, PicoScope, and SCPI function generator
  - A1/A2 allostatic feedback and efference-copy injection in hardware/firmware
"""

import time
import numpy as np

class LaboratoryParametersConfig:
    """Preregistered optimal laboratory parameters according to P0_Distilled v0.1."""
    # Voltage and compliance
    V_OPERATING_NOMINAL = 1.0       # Volts (nominal stimulus voltage)
    V_COMPLIANCE_MAX = 1.5          # Volts (maximum safety voltage)
    I_COMPLIANCE_MAX = 1e-3         # Ampere (1 mA compliance current)
    I_OPERATING_RANGE = (10e-6, 500e-6)  # Ampere (normal operating range)

    # Sampling and timing
    SAMPLE_RATE_DMM_HZ = 1000.0     # Hz (DMM sampling frequency)
    SAMPLE_RATE_PICO_MHZ = 1.0      # MHz (PicoScope sampling frequency)
    TIME_WINDOW_MS = 100.0          # ms (acquisition window per frame)

    # Noise and criticality (edge of chaos)
    SIGMA_NOISE_OPTIMAL = 0.10     # 10% amplitude of the 1/f percolative noise
    ALPHA_NOISE_1F = 1.0            # 1/f^alpha spectral exponent
    EDGE_OF_CHAOS_FREQ_BAND = (10.0, 1000.0)  # Hz (Chua local activation band)

    # A1/A2 allostatic feedback
    EFFERENCE_COPY_GAIN_GAMMA = 0.8
    ALLOSTASIC_BETA = 0.5
    FEEDBACK_LATENCY_MS = 1.0


def generate_1f_noise(n_samples, dt, alpha=1.0, sigma=0.10, rng=None):
    """
    Gaussian noise with power spectral density S(f) ~ 1/f**alpha, rescaled to standard
    deviation `sigma`. Generated by shaping white noise in the frequency domain; the DC
    component, where 1/f diverges, is set to zero.
    """
    if n_samples < 4:
        raise ValueError(f"n_samples must be at least 4, got {n_samples}")
    if dt <= 0:
        raise ValueError(f"dt must be positive, got {dt}")
    rng = np.random.default_rng() if rng is None else rng
    white_noise = rng.normal(0, 1, n_samples)
    fft_noise = np.fft.rfft(white_noise)
    freqs = np.fft.rfftfreq(n_samples, d=dt)
    fft_noise[0] = 0.0
    freqs[0] = 1.0
    shaped = np.fft.irfft(fft_noise / (freqs ** (alpha / 2.0)), n=n_samples)
    return (shaped / (np.std(shaped) + 1e-12)) * sigma


def mock_dmm_carrier(t):
    """Deterministic 5 Hz current carrier of the mock DMM (A), without noise."""
    return 100e-6 * (1.0 + 0.5 * np.sin(2 * np.pi * 5.0 * t))


class KeithleyDMMDriverV2:
    """
    Driver for a Keithley SourceMeter (e.g. 2400) with compliance limits set on connection.

    The real-instrument path (mock=False) has only been tested against a fake VISA resource
    that records the commands (test_hardware_session.py), not against an instrument. On
    connection it sets the current compliance and the overvoltage protection before any other
    command, reads both back, and closes the connection and raises if they do not match.
    Use it as a context manager, or call close(), to release the instrument.
    """
    def __init__(self, resource_name="GPIB0::24::INSTR", config=LaboratoryParametersConfig, mock=True, seed=None,
                 resource_manager=None):
        self.resource_name = resource_name
        self.config = config
        self.mock = mock
        self.connected = False
        self.inst = None
        self.rng = np.random.default_rng(seed)
        self._resource_manager = resource_manager

    def connect(self):
        if self.mock:
            self.connected = True
            return f"MOCK_KEITHLEY_2400 (Configured: V_comp={self.config.V_COMPLIANCE_MAX}V, I_comp={self.config.I_COMPLIANCE_MAX*1e3}mA)"
        if self._resource_manager is None:
            import pyvisa
            self._resource_manager = pyvisa.ResourceManager()
        self.inst = self._resource_manager.open_resource(self.resource_name)
        # Safety limits first, before any other command
        self.inst.write(f":SENS:CURR:PROT {self.config.I_COMPLIANCE_MAX}")
        self.inst.write(f":SOUR:VOLT:PROT {self.config.V_COMPLIANCE_MAX}")
        current_limit = float(self.inst.query(":SENS:CURR:PROT?"))
        voltage_limit = float(self.inst.query(":SOUR:VOLT:PROT?"))
        if current_limit > self.config.I_COMPLIANCE_MAX or voltage_limit > self.config.V_COMPLIANCE_MAX:
            self.close()
            raise RuntimeError(
                f"compliance not applied: instrument reports {current_limit} A / {voltage_limit} V, "
                f"requested {self.config.I_COMPLIANCE_MAX} A / {self.config.V_COMPLIANCE_MAX} V")
        self.connected = True
        return self.inst.query("*IDN?")

    def close(self):
        """Release the instrument (no-op for the mock)."""
        if self.inst is not None:
            self.inst.close()
            self.inst = None
        self.connected = False

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()
        return False

    def read_current_stream(self, n_samples=1000):
        """Reads a current stream I(t), injecting 1/f percolative noise calibrated at the edge of chaos."""
        if not self.connected:
            raise RuntimeError("Device not connected. Call connect() before reading.")
        if self.mock:
            if n_samples < 4:
                raise ValueError(f"n_samples must be at least 4, got {n_samples}")
            dt = 1.0 / self.config.SAMPLE_RATE_DMM_HZ
            t = np.linspace(0, n_samples * dt, n_samples)

            noise_1f = generate_1f_noise(n_samples, dt, alpha=self.config.ALPHA_NOISE_1F,
                                         sigma=self.config.SIGMA_NOISE_OPTIMAL, rng=self.rng)

            # Deterministic carrier modulated by the 1/f noise
            i_t = mock_dmm_carrier(t) * (1.0 + noise_1f)

            # Hard compliance protection limit
            i_t = np.clip(i_t, 0, self.config.I_COMPLIANCE_MAX)
            return i_t
        data_str = self.inst.query(":TRACE:DATA?")
        return np.array([float(val) for val in data_str.split(',') if val.strip()])


PICOSCOPE_NOT_IMPLEMENTED = (
    "real PicoScope acquisition is not implemented: only the mock (mock=True) is available. "
    "A real driver needs the vendor SDK (picosdk)."
)


class PicoScopeOscilloscopeDriverV2:
    """Driver for a high-sample-rate PicoScope oscilloscope. Only the mock is implemented."""
    def __init__(self, channels=("A", "B"), config=LaboratoryParametersConfig, mock=True, seed=None):
        self.channels = channels
        self.config = config
        self.mock = mock
        self.connected = False
        self.rng = np.random.default_rng(seed)

    def connect(self):
        if not self.mock:
            raise NotImplementedError(PICOSCOPE_NOT_IMPLEMENTED)
        self.connected = True
        return f"MOCK_PICOSCOPE_5000 (Configured: SampleRate={self.config.SAMPLE_RATE_PICO_MHZ}MHz)"

    def close(self):
        self.connected = False

    def acquire_waveform(self, time_window_ms=None):
        """Acquires the voltage waveforms V(t) with Chua band and voltage protection."""
        if not self.mock:
            raise NotImplementedError(PICOSCOPE_NOT_IMPLEMENTED)
        if not self.connected:
            raise RuntimeError("Device not connected. Call connect() before acquiring.")
        if time_window_ms is None:
            time_window_ms = self.config.TIME_WINDOW_MS

        n_pts = int(time_window_ms * 1e-3 * self.config.SAMPLE_RATE_PICO_MHZ * 1e6)
        t = np.linspace(0, time_window_ms * 1e-3, n_pts)

        # Voltage signal with edge-of-chaos resonance
        v_a = self.config.V_OPERATING_NOMINAL * np.cos(2 * np.pi * 50 * t) + self.rng.normal(0, 0.05, n_pts)
        v_b = 0.8 * np.sin(2 * np.pi * 50 * t + np.pi/4) + self.rng.normal(0, 0.02, n_pts)

        # Safety clipping at V_COMPLIANCE_MAX
        v_a = np.clip(v_a, -self.config.V_COMPLIANCE_MAX, self.config.V_COMPLIANCE_MAX)
        v_b = np.clip(v_b, -self.config.V_COMPLIANCE_MAX, self.config.V_COMPLIANCE_MAX)

        return {"time": t, "channel_A": v_a, "channel_B": v_b}


class NeuromorphicHardwareInterfaceV2:
    """Integrated interface that automatically applies the optimal laboratory parameters."""
    def __init__(self, config=LaboratoryParametersConfig, mock=True):
        self.config = config
        self.dmm = KeithleyDMMDriverV2(config=config, mock=mock)
        self.pico = PicoScopeOscilloscopeDriverV2(config=config, mock=mock)

    def initialize_session(self):
        # The oscilloscope first: its real path is not implemented, and it must fail before
        # a real source-meter is opened.
        info_pico = self.pico.connect()
        info_dmm = self.dmm.connect()
        return (f"=== ADVANCED HARDWARE SESSION INITIALIZED (P0_Distilled v0.1) ===\n"
                f" - DMM: {info_dmm}\n"
                f" - PicoScope: {info_pico}\n"
                f" - Compliance V/I: Max {self.config.V_COMPLIANCE_MAX}V / {self.config.I_COMPLIANCE_MAX*1e3}mA\n"
                f" - 1/f Noise Calibration: sigma_noise = {self.config.SIGMA_NOISE_OPTIMAL} (edge of chaos)\n"
                f" - Efference Feedback: Gain gamma = {self.config.EFFERENCE_COPY_GAIN_GAMMA}\n"
                f"=========================================================================")

    def close(self):
        self.dmm.close()
        self.pico.close()

    def __enter__(self):
        self.initialize_session()
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()
        return False

    def get_realtime_frame(self, n_samples=1000):
        """Extracts a coordinated frame of current I(t) and voltage V(t), ready for the valence computation."""
        i_t = self.dmm.read_current_stream(n_samples=n_samples)
        v_data = self.pico.acquire_waveform()
        return {
            "current_I": i_t,
            "voltage_V": v_data["channel_A"],
            "time_dmm": np.linspace(0, n_samples / self.config.SAMPLE_RATE_DMM_HZ, n_samples),
            "time_pico": v_data["time"]
        }


if __name__ == "__main__":
    hw = NeuromorphicHardwareInterfaceV2(mock=True)
    print(hw.initialize_session())
    frame = hw.get_realtime_frame(n_samples=1000)
    print(f"Frame acquired: {len(frame['current_I'])} I(t) points [Mean I = {np.mean(frame['current_I'])*1e6:.2f} uA], {len(frame['voltage_V'])} V(t) points.")
