"""
thermodynamic_valence.py
=========================
Metrology script for neuromorphic substrates and digital twin (P0_Distilled v0.1)

Author: Lakatosian Research Programme (P0_Distilled v0.1)
Description:
  This script acts as a "metrological ruler" for processing physical time series
  measured from analog substrates (or simulated via SDE in a digital twin).

  Computes:
  1. Heuristic dissipation proxies sigma_hk and sigma_ex. These are NOT the
     Hatano-Sasa housekeeping/excess entropy production rates: sigma_hk scales as
     sigma_noise**2 / dt, so it depends on the integration step, and the true
     housekeeping rate of this one-variable model is identically zero. A
     thermodynamically meaningful estimator (e.g. Sekizawa, Ito & Oizumi, Phys.
     Rev. X 14, 041003, 2024, for linear Langevin systems) needs at least two
     coupled state variables and is not implemented yet.
  2. Non-parametric k-NN estimate of the Kullback-Leibler divergence (D_KL) for the
     allostatic niche.
  3. Predictive gain of the efference copy (G_pred) generated by level A2, as defined
     in P2_SelfAgency.tex §5.4, on delay-embedded densities. In this simulation A2 does
     not feed back into A1, so ablating the efference copy changes the measurement,
     not the dynamics.
  4. Integrated thermodynamic and allostatic valence functional Psi(t).
"""

import numpy as np
from scipy.spatial import KDTree

def simulate_neuromorphic_substrate_sde(n_steps=10000, dt=0.001, seed=42):
    """
    Simulates the stochastic dynamics of a two-level neuromorphic substrate (A1/A2)
    by Euler-Maruyama integration of an SDE with additive noise.
    """
    if n_steps < 2:
        raise ValueError(f"n_steps must be at least 2, got {n_steps}")
    if dt <= 0:
        raise ValueError(f"dt must be positive, got {dt}")
    # Local generator: same stream as the former np.random.seed(seed), without touching
    # the global NumPy state of the caller.
    rng = np.random.RandomState(seed)

    # Material parameters (Mott / diffusive memristor)
    a, b = -1.2, 0.8  # Local activation parameters (edge of chaos)
    sigma_noise = 0.15  # Additive white Gaussian noise; the 1/f noise lives in hardware_driver_v2.py

    x_A1 = np.zeros(n_steps)
    s_obs = np.zeros(n_steps)
    s_pred = np.zeros(n_steps)

    x_val = 0.1
    x_A1[0] = x_val
    # No noise draw at t = 0, so the random stream of the loop is unchanged.
    s_obs[0] = x_val
    s_pred[0] = x_val
    for t in range(1, n_steps):
        # SDE for the primary level A1
        dW = rng.normal(0, np.sqrt(dt))
        # With additive noise the Milstein correction 0.5*g*g'*(dW**2 - dt) vanishes
        # (g' = 0), so Milstein reduces to Euler-Maruyama (Higham 2001).
        dx = (a * x_val + b * np.tanh(x_val) + np.sin(t * dt * 2.0)) * dt + sigma_noise * dW
        x_val += dx
        x_A1[t] = x_val

        # Real sensory reafference
        s_obs[t] = x_val + rng.normal(0, 0.05)

        # Efference copy (level A2) - allostatic prediction
        s_pred[t] = x_A1[t-1] + (a * x_A1[t-1] + b * np.tanh(x_A1[t-1])) * dt

    return x_A1, s_obs, s_pred, dt

def estimate_kl_divergence_knn(p_samples, q_samples, k=5):
    """
    Non-parametric k-NN estimate of the Kullback-Leibler divergence D_KL(P || Q),
    based on KDTree (Kraskov et al. / Perez-Cruz).

    Negative estimates, which sampling noise produces when P and Q are close, are clipped
    to 0 (as in the Rust engine). G_pred is a difference of two such estimates and
    inherits the clipping when both are small.
    """
    p_samples = np.asarray(p_samples, dtype=float)
    q_samples = np.asarray(q_samples, dtype=float)
    p_samples = np.atleast_2d(p_samples).T if p_samples.ndim == 1 else p_samples
    q_samples = np.atleast_2d(q_samples).T if q_samples.ndim == 1 else q_samples

    n, d = p_samples.shape
    m, d_q = q_samples.shape
    if d != d_q:
        raise ValueError(f"p_samples and q_samples differ in dimension: {d} vs {d_q}")
    if n <= k + 1 or m < k:
        raise ValueError(f"need more than k + 1 = {k + 1} samples of P and at least k = {k} of Q, got {n} and {m}")
    if not (np.all(np.isfinite(p_samples)) and np.all(np.isfinite(q_samples))):
        raise ValueError("samples contain NaN or infinite values")

    tree_p = KDTree(p_samples)
    tree_q = KDTree(q_samples)

    # Distances to the k-th nearest neighbours in P
    r_p, _ = tree_p.query(p_samples, k=k+1)
    r_k_p = r_p[:, -1]

    # Distances to the k-th nearest neighbours in Q
    r_q, _ = tree_q.query(p_samples, k=k)
    r_k_q = r_q[:, -1]

    # Avoid division by zero
    r_k_p = np.maximum(r_k_p, 1e-12)
    r_k_q = np.maximum(r_k_q, 1e-12)

    kl_est = (d / n) * np.sum(np.log(r_k_q / r_k_p)) + np.log(m / (n - 1.0))
    return max(0.0, float(kl_est))

def delay_embed(signal, tau_steps):
    """
    Two-dimensional delay embedding (s(t), s(t - tau)) of a one-dimensional signal.
    Densities compared in this space depend on temporal structure, not only on the
    distribution of values, as the phase-space densities of P2_SelfAgency.tex (§5.4) do.
    """
    signal = np.asarray(signal, dtype=float)
    return np.column_stack((signal[tau_steps:], signal[:-tau_steps]))


def calculate_thermodynamic_valence(x_A1, s_obs, s_pred, dt, alpha=1.0, beta=0.5, gamma=0.8,
                                    tau_steps=10, niche_seed=12345, niche_samples=None):
    """
    Computes the valence functional Psi(t) from two heuristic dissipation proxies,
    the allostatic divergence, and the predictive gain of the efference copy.

    G_pred follows the definition of P2_SelfAgency.tex (§5.4):
        G_pred = D_KL(p_obs || p_ref) - D_KL(p_obs || p_pred),
    estimated on delay-embedded densities (tau_steps). The digital twin has no
    actuation, so the free-running reference p_ref is stood in for by the target niche.
    The niche samples are drawn from a fixed seed, so equal inputs give equal outputs;
    niche_samples (one per time point) replaces them, e.g. to compare with the Rust engine,
    which draws its niche from a different generator.
    """
    x_A1, s_obs, s_pred = (np.asarray(a, dtype=float) for a in (x_A1, s_obs, s_pred))
    if not (x_A1.ndim == s_obs.ndim == s_pred.ndim == 1):
        raise ValueError("x_A1, s_obs and s_pred must be one-dimensional")
    if not (len(x_A1) == len(s_obs) == len(s_pred)):
        raise ValueError(f"x_A1, s_obs and s_pred must have equal length, got {len(x_A1)}, {len(s_obs)}, {len(s_pred)}")
    if dt <= 0:
        raise ValueError(f"dt must be positive, got {dt}")
    if tau_steps < 1:
        raise ValueError(f"tau_steps must be at least 1, got {tau_steps}")
    min_length = tau_steps + 7  # the k-NN estimators (k = 5) need at least 7 embedded points
    if len(x_A1) < min_length:
        raise ValueError(f"series too short: {len(x_A1)} samples, need at least {min_length} for tau_steps = {tau_steps}")
    if not all(np.all(np.isfinite(a)) for a in (x_A1, s_obs, s_pred)):
        raise ValueError("x_A1, s_obs and s_pred must not contain NaN or infinite values")

    # 1. Heuristic dissipation proxies -- NOT Hatano-Sasa quantities (see module docstring).
    # Their ratio, and hence Psi, changes with dt: compare results only at equal dt.
    dx = np.diff(x_A1) / dt
    sigma_hk = np.var(dx)  # Proxy: variance of the finite-difference velocity (~ sigma_noise**2 / dt)
    sigma_ex = np.mean(np.abs(dx * x_A1[:-1]))  # Proxy: mean |velocity * state|

    # 2. Target allostatic niche p_target ~ N(0, 0.2), from a fixed seed so that it
    # does not add run-to-run noise to the comparison between conditions.
    if niche_samples is None:
        p_target = np.random.default_rng(niche_seed).normal(0.0, 0.2, size=(len(x_A1), 1))
    else:
        p_target = np.asarray(niche_samples, dtype=float).reshape(-1, 1)
        if len(p_target) != len(x_A1) or not np.all(np.isfinite(p_target)):
            raise ValueError("niche_samples must be finite, with one sample per time point")
    x_samples = np.atleast_2d(x_A1).T

    d_kl_allostatic = estimate_kl_divergence_knn(x_samples, p_target, k=5)

    # 3. Predictive gain of the efference copy (G_pred), P2 §5.4: the prediction is
    # scored against the observations, not against the niche.
    p_ref = delay_embed(p_target[:, 0], tau_steps)
    obs_embedded = delay_embed(s_obs, tau_steps)
    pred_embedded = delay_embed(s_pred, tau_steps)

    d_kl_reference = estimate_kl_divergence_knn(obs_embedded, p_ref, k=5)
    d_kl_prediction = estimate_kl_divergence_knn(obs_embedded, pred_embedded, k=5)

    g_pred = d_kl_reference - d_kl_prediction

    # 4. Integrated valence functional Psi(t) -- PRACTICAL PROXY, not the formal
    # definition in P1_Main.tex Appendix F (Psi = alpha*(S_ex_dot/S_crit_dot) -
    # beta*(delta_S_hk_dot/S_crit_dot) + gamma*G_pred). The formal form requires a
    # hardware-calibrated critical entropy-production rate (S_crit_dot) that this
    # digital twin does not yet estimate; this proxy substitutes a log-ratio of the
    # raw dissipative components and a KL-divergence from the target niche instead.
    # The two forms are NOT algebraically equivalent -- see P1_Main Appendix F for
    # the precise relation and rationale before treating this as ground truth.
    psi = alpha * np.log(1.0 + (sigma_ex / (sigma_hk + 1e-8))) - beta * d_kl_allostatic + gamma * g_pred

    return {
        "sigma_ex": float(sigma_ex),
        "sigma_hk": float(sigma_hk),
        "d_kl_allostatic": float(d_kl_allostatic),
        "g_pred": float(g_pred),
        "psi_valence": float(psi)
    }

if __name__ == "__main__":
    print("=== RUNNING ADVANCED DIGITAL TWIN METROLOGY (P0_Distilled v0.1) ===")
    x_A1, s_obs, s_pred, dt = simulate_neuromorphic_substrate_sde(n_steps=10000)
    res = calculate_thermodynamic_valence(x_A1, s_obs, s_pred, dt)

    print(f"Time points processed: {len(x_A1)}")
    print(f"Mean state of substrate A1 x(t): {np.mean(x_A1):.4f}")
    print(f"Excess-dissipation proxy sigma_ex: {res['sigma_ex']:.4f}")
    print(f"Housekeeping-dissipation proxy sigma_hk (dt-dependent): {res['sigma_hk']:.4f}")
    print(f"Allostatic divergence D_KL(P||P_target): {res['d_kl_allostatic']:.4f}")
    print(f"Predictive gain of the efference copy G_pred: {res['g_pred']:.4f}")
    print(f"-> INTEGRATED VALENCE FUNCTIONAL Psi(t): {res['psi_valence']:.4f}")
    print("=========================================================================")
